global:
  scrape_interval: 5s
  evaluation_interval: 5s

  external_labels:
    monitor: 'monitoring'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'internal'

  - job_name: jaeger
    static_configs:
      - targets: ['jaeger:14269']
        labels:
          group: 'internal'

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          group: 'host'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          group: 'docker'

  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres_exporter:9187"]
        labels:
          group: 'database'

  - job_name: 'mongo_exporter'
    static_configs:
      - targets: ["mongo_exporter:9216"]
        labels:
          group: 'database'

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']
        labels:
          group: 'database'

  - job_name: 'rabbitmq_server'
    static_configs:
      - targets: ['rabbitmq:15692']
        labels:
          group: 'rabbitmq'

  - job_name: 'rabbitmq_exporter'
    static_configs:
      - targets: ['rabbitmq_exporter:9090']
        labels:
          group: 'rabbitmq_exporter'
